= Coverages: Before and After WCS

This article is a blog stating a personal opinion.

There are many formats for raster/grid/array data.  Each vendor supports many formats.  GDAL lists 168 link:https://gdal.org/drivers/raster/index.html[Raster drivers].  How to approach this diversity in an efficient and effective manner?  The different formats exist for various reasons: specific use cases, efficiency enhancements, and independent invention.  The link:https://portal.opengeospatial.org/files/?artifact_id=19820[OGC Geospatial Coverage Abstract Standard], also now issued by ISO, defines a data representation to increase interoperability of raster encoding formats.

This ESIP/OGC Sprint is an opportunity to recall how the Geospatial Coverages model was defined to address raster diversity. The Coverages Abstract Spec has a solid research basis reflected initially in an NCGIA report and later publications:

- link:http://www.ncgia.ucsb.edu/Publications/Varenius_Reports/Ontology_of_Fields.pdf[The Ontology of Fields] - Peuquet, Smith, and Brogaard, NCGIA, 1998
- link:https://www.tandfonline.com/doi/full/10.1080/13658810600965271[Towards a general theory of geographic representation in GIS] - Goodchild, Yuan & Cova 2007
- link:https://pdfs.semanticscholar.org/a192/5854e1c0b2e9075249a84d330b5a0e9d6d6e.pdf?_ga=2.76352150.2480309.1575582200-578620410.1575582200[Towards standardised dynamic and 3D field representations] - H. Ledoux, 2008

The Geospatial Coverages Standard was a basis for OGC Web Coverage Services (WCS) and OGC Coverage Implementation Schema (CIS).  WCS provided a web services implementation that is used operationally in Geospatial Coverage Data Cube implementations: petabyte data cubes, with 50M assets/datasets serving 10^5 - 10^7 dataset accesses per month.  Now what is needed is to step back from WCS and look at modeling spatial information as fields.

How can the Coverages AS provide insight for a Coverage API? The OGC API Coverages approaches aim to improve on WCS using resource oriented approaches.  The coverage/field data model provides a representation for harmonizing remote sensing “raster wars” with geospatial info more broadly. Now is the time to affect the OGC API-Coverages development to go beyond the WCS limitations and achieve the semantically enabled abilities for Coverages using the OGC/ISO Geospatial Coverages Abstract Spec.

The API must support gridded and non-gridded data, n-dimensional data, continuous and categorical data.  The data should be represented as a semantic description of the geographic phenomena that are represented by Coverages. The API needs to provide information about the spatial-temporal domain of the data, with the simplest case being CRS by reference.  The API needs to represent the range information where the record may be a single data value parameter or the record may be a more complex vector or tensor record.  The goal is to satisfy user-queries efficiently and rapidly.  Analysis on coverages needs to developed for an API approach based on the abstract specifications for Coverages and Processing as well as OPeNDAP, GeoXarray/ZARR, R-spatial and other modern software development environments.

link:https://en.wikipedia.org/wiki/Format_war[Raster Wars] are well known in technology development.  Also well known is that every generation reinvents so of what came before.  Every generation of teenagers are convinced they invented sex.  There is a key balance of standards and innovation: Too much standards provides stagnation; Ignoring standards often results in reinvention. Let's define an API for Coverages that builds on research on coverages and field models for representing geographic data while utilizing the latest software development tools for APIs.




A footnote: An initial implementation spec based on the Geospatial Coverages Abstract Specification was the link:https://www.opengeospatial.org/standards/gc[OpenGIS Implementation Specification: Grid Coverages, OGC document 01-004] written and implemented by PCI Geomatics, Cadcorp, Oracle.


(This blog was written by George Percivall.  It includes text from a draft document by Ingo Simonis)
